services:
    mysql:
        image: mysql:latest
        container_name: inventory-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: inventory_db
            MYSQL_USER: inventory_user
            MYSQL_PASSWORD: inventory_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: arm64v8/phpmyadmin # ✅ ARM64-compatible image
        container_name: inventory-phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"

volumes:
    mysql_data:
