version: '3.9' # Using the latest stable version of Docker Compose

services:
    mysql:
        image: mysql:latest # Uses the latest MySQL version
        container_name: fashion-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: fashion_db
            MYSQL_USER: fashion_user
            MYSQL_PASSWORD: fashion_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest # Uses the latest phpMyAdmin version
        container_name: fashion-phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"

volumes:
    mysql_data:
